# Generated by Django 3.2.6 on 2021-08-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='image_url',
            field=models.URLField(max_length=1000),
        ),
    ]
