# Generated by Django 3.2.6 on 2021-08-18 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasehistory',
            old_name='count',
            new_name='purchased_price',
        ),
        migrations.RenameField(
            model_name='purchasehistory',
            old_name='product_option',
            new_name='purchased_product',
        ),
        migrations.RenameField(
            model_name='purchasehistory',
            old_name='purchase_price',
            new_name='purchased_quantity',
        ),
        migrations.RenameField(
            model_name='purchasehistory',
            old_name='purchase_time',
            new_name='purchased_time',
        ),
        migrations.AlterField(
            model_name='follow',
            name='followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='users.user'),
        ),
    ]
