# Generated by Django 3.2.6 on 2021-08-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='paypal_payer_id',
            field=models.CharField(default='na', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='paypal_payment_id',
            field=models.CharField(default='na', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='paypal_payment_token',
            field=models.CharField(default='na', max_length=200),
            preserve_default=False,
        ),
    ]
