# Generated by Django 3.2.6 on 2021-08-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210818_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='kakao_email',
            new_name='kakao_nickname',
        ),
    ]
