# Generated by Django 3.2.6 on 2021-08-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_kakao_email_user_kakao_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='kakao_nickname',
            new_name='kakao_email',
        ),
    ]
