# Generated by Django 3.2.6 on 2021-08-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210818_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='model_name',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='producer',
        ),
    ]
